### ISSUE TITLE
Should the shebang of the scripts be `#!/bin/bash` instead of `#!/bin/sh`?

### ISSUE THREAD

**Issue by daniel-webstep** [serverpod/serverpod#2743] opened 2024-09-12 10:17 UTC
**Describe the bug**
When I tried to run the `util/pub_get_all` (and some of the other scripts) in a VS Code `devcontainer` I had issues with `declare -a` statements throwing errors like: 
```
PUB UPGRADE ALL
./util/pub_get_all: 28: Syntax error: "(" unexpected
```

I tracked it down and found out that Bourne shells doesn't have this syntax for arrays: [unix.stackexchange.com: arrays-in-unix-bourne-shell](https://unix.stackexchange.com/questions/137566/arrays-in-unix-bourne-shell). When I changed the shebang to `#!/bin/bash`, the script completed successfully.

Noteworthy is that the script was able to create the array on my mac, which has a different `bash` version.

**To Reproduce**
1. From a VS code `devcontainer` or a Ubuntu machine with similar specs
2. run `./util/pub_get_all`

**Expected behavior**
Scripts complete successfully and in the particular case given above, all relevant libraries are pulled successfully.

**Serverpod versions**
 -  _CLI Version:_ Not relevant, but I'm running from `main`.
 - _Library version:_ Not relevant, but I'm running from `main`.

**Platform information**
The devcontainer I'm using have the following config:
```
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
...
```

```
$0 --version
GNU bash, version 5.2.21(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

My mac setup
```
$ sw_vers
ProductName:            macOS
ProductVersion:         14.5
BuildVersion:           23F79
```
```
$ $0 --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin23)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Additional context**
It might be other issues with changing the shebang for all scripts. I don't have experience enough about the serverpod build environment to know if it is sound to update them all in one go.

**Comment by SandPod** [comment] 2024-09-13 07:56
I believe you are correct, it is probably just a happy coincidence this is working for us.

As long as this works on MacOS, Linux and GitBash in Windows (LSS) then this change should be fine.

**Comment by dannejosefsson** [comment] 2024-09-13 15:55
I can definitely create a PR for this. But the caveat is that I have quite limited testing capabilities when it comes to Windows machines though as well as knowledge about the innards of the different scripts.

**Comment by dannejosefsson** [comment] 2024-09-20 06:47
@Isakdl , since the PR is merged, I guess we should close this one now.

**Comment by Isakdl** [comment] 2024-09-20 07:28
Ah yes thank you, will do. (tip for the future if you write Closes: #ticketNumber) in the PR the issue is closed automatically :).

**Closed by Isakdl** 2024-09-20 07:28 UTC
Labels: area: internal tooling
