### ISSUE TITLE
persist mark leads to null error

### ISSUE THREAD

**Issue by mades5** [serverpod/serverpod#2658] opened 2024-08-23 09:08 UTC
**Describe the bug**
I marked a field with persist mark:

 `field: String?, !persist`

when I create an enpoint:

`Future<List<ModelName>> find(Session session) async {
    return await ModelName.db.find(session);
  }`

I got an error:

`field: jsonSerialization['field'] as String?`

`type 'Null' is not a subtype of type 'String' in type cast`

**To Reproduce**
1. create a model with a persist field
2. create an endpoint
3. run generate and migrations
4. call endpoint from app

**Serverpod versions**
 -  _CLI Version:_ 2.0.2
 - _Library version:_ 2.0.2

Any ideas to fix this?

**Comment by SandPod** [comment] 2024-08-23 09:10
Hey @mades5 👋 

Could you provide a complete model with the minimum fields required to reproduce the issue along with the queries run to encounter this issue?
This will help us debug this issue even faster.

**Comment by mades5** [comment] 2024-08-23 09:14
Hey @SandPod,

thank you for your quick reply.
My model just has two fields. The migrations just creates that one without the persist mark but I think the generated model.dart file awaits the field from database

`factory ModelName.fromJson(Map<String, dynamic> jsonSerialization) {
    return ModelName(
      id: jsonSerialization['id'] as int?,
      name: jsonSerialization['name'] as String,
      field: jsonSerialization['field'] as String?,
    );
  }`

the field line produces the error

**Comment by mades5** [comment] 2024-08-23 09:24
when I replace the line

`field: jsonSerialization['field'] as String?`

with

`field: ''`

everything works till next generation

**Comment by SandPod** [comment] 2024-08-23 09:25
This is the generated code.

Please give us the Model code you have defined (or a minimum example) and the exact query sequence that produces the error.

This allows us to reproduce the error on our side.

**Comment by mades5** [comment] 2024-08-23 09:26
`class: ModelName
table: modelname
fields:
  name: String
  field: String?, !persist
`

**Comment by klkucaj** [comment] 2024-08-23 10:08
@mades5 i cant reproduct this issue:

`class ExampleEndpoint extends Endpoint {
  Future<List<ModelName>> find(Session session) async {
    return await ModelName.db.find(session);
  }
}

.......
class: ModelName 
table: modelname 
fields: 
  name: String 
  field: String?, !persist 
  
.......
 Future<List<ModelName>> find(Session session) async {
    return await ModelName.db.find(session);
  }
  
 ......
 CREATE TABLE "modelname" (
    "id" bigserial PRIMARY KEY,
    "name" text NOT NULL
);
  
`

and the log:
METHOD CALL: example.find duration: 6ms numQueries: 0 authenticatedUser: null

and this from flutter side when i call find method:

![Screenshot 2024-08-23 at 12 07 47 PM](https://github.com/user-attachments/assets/378ff5e7-e5b1-4dea-adbf-3791763f8188)

**Comment by mades5** [comment] 2024-08-23 10:12
Hi @klkucaj,

could you check the erc/generated/modelname.dart and the

factory ModelName.fromJson(Map<String, dynamic> jsonSerialization)

method?

Mine looks like this

```
factory ModelName.fromJson(Map<String, dynamic> jsonSerialization) {
return ModelName(
      id: jsonSerialization['id'] as int?,
      name: jsonSerialization['name'] as String,
      field: jsonSerialization['field'] as String?,
    );
```

**Comment by klkucaj** [comment] 2024-08-23 10:14
@mades5 exactly the same:

 ```
factory ModelName.fromJson(Map<String, dynamic> jsonSerialization) {
    return ModelName(
      id: jsonSerialization['id'] as int?,
      name: jsonSerialization['name'] as String,
      field: jsonSerialization['field'] as String?,
    );
  }
```

**Comment by mades5** [comment] 2024-08-23 10:20
ok, this is crazy, I always get

```
type 'Null' is not a subtype of type 'String' in type cast
#0      new ModelName.fromJson (package:test_server/src/generated/modelname.dart:36:47)
#1      Protocol.deserialize (package:test_server/src/generated/protocol.dart:812:26)
#2      DatabaseConnection._deserializedMappedQuery.<anonymous closure> (package:serverpod/src/database/adapters/postgres/database_connection.dart:497:57)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#5      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#6      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#7      new List.of (dart:core-patch/array_patch.dart:39:18)
```

and the line 36 in modelname.dart is

`field: jsonSerialization['field'] as String?,`


I try to create a new project and reproduce the error here.

**Comment by mades5** [comment] 2024-08-23 11:50
ok, with a new project the error i gone but I cannot find a difference between them. Strange

**Comment by SandPod** [comment] 2024-08-23 12:08
Sounds strange.

Could it be the state of the database?
I will close this issue then since we don't have a valid repro.

**Closed by SandPod** 2024-08-23 12:08 UTC
Labels: question

**Comment by mades5** [comment] 2024-08-23 12:10
Thanks for your help. The 1st project works again after restarting a the gui and cleaning the flutter install.

**Comment by SandPod** [comment] 2024-08-23 12:14
Then it might have been a cached Protocol file somewhere.

**Comment by mades5** [comment] 2024-08-23 12:17
I think it was cache problem

the error was: `type 'Null' is not a subtype of type 'String' in type cast`

but the definition is `field: String?, !persist`

Thanks for help
