### ISSUE TITLE
Test Framework with mocking

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1008] opened 2023-06-09 07:33 UTC
Create a test framework so that we can run an endpoint in isolation for tests, complete with mocking the Session object, auth, etc.

### Discussed in https://github.com/serverpod/serverpod/discussions/1007

<div type='discussions-op-text'>

<sup>Originally posted by **Orchius83** June  9, 2023</sup>
Morning everyone, I'm using Serverpod a lot and now I'm starting a big project on it. 
I'm feeling that I miss the latest step to be totally productive that is the ability to test with a Mocked Session to save and retrieve Entities in my tests. 
Is there anything that is in development right now?
Thank</div>

**Comment by SimonErich** [comment] 2024-01-06 15:25
@Isakdl I am in the same boat.
Just out of interest: Did you find a method to do proper and simple testing?

I looked at a few examples in the repo tests itself. Especially the e2e tests look promising for a start, but it would be great, if there was less overhead of course. :)

**Comment by SandPod** [comment] 2024-08-21 07:33
Closing this as a duplicate of: https://github.com/serverpod/serverpod/issues/2494

**Closed** 2024-08-21 07:33 UTC
Labels: enhancement
