### ISSUE TITLE
API only relationships are broken 

### ISSUE THREAD

**Issue by kieran-novarca** [serverpod/serverpod#1778] opened 2024-01-18 09:11 UTC
**Describe the bug**
It seems that when you have a class that is defined in the yaml files which is not a database class (API only), that relates to another class which is also not a database class (API only), the generated code is causing errors. 

**To Reproduce**
1. Create a protocol file for a class that does not have the table attribute
2. Create a second protocol file for a class that does not have the table attribute
3. Add a field to one of the classes that is of the type of the other class you created 
4. Run serverpod generate, your generated code will error. 

**Expected behavior**
No errors

**Screenshots**
![image](https://github.com/serverpod/serverpod/assets/120369588/70f42c41-6d25-4249-b218-d3890d5989d6)
![image](https://github.com/serverpod/serverpod/assets/120369588/aacb071b-615f-4552-8c87-802d0787ad9f)

**Serverpod versions**
 -  _CLI Version: 1.2
 - _Library version: 1.2

**Comment by SandPod** [comment] 2024-01-18 09:30
Hi, thanks for the report @kieran-novarca.

Could you provide examples of protocol files that causes this issue?

**Comment by Isakdl** [comment] 2024-01-18 09:53
I'm not able to reproduce this issue with the following files:


```yaml
class: FieldInputType
fields:
  valueType: InputValueType
  name: String
  description: String
  thumbnailUrl: String
```

```yaml
class: InputValueType
fields:
  name: String
```

**Comment by Isakdl** [comment] 2024-01-18 10:14
In your code this part  in the factory constructor looks strange: `Map<Object, Object> map,`. It should not be possible for this code to be generated, we will only ever insert optional params in the factory constructor. Do you still have this error if you manually remove that code?

**Comment by kieran-novarca** [comment] 2024-01-18 10:31
Here are our protocol files, I will get my dev that originally found this to continue replying to this issue:

![Screenshot 2024-01-18 at 10 29 38](https://github.com/serverpod/serverpod/assets/120369588/daa14cd0-31a3-476b-90f4-a8d6de2d09d0)
![Screenshot 2024-01-18 at 10 30 18](https://github.com/serverpod/serverpod/assets/120369588/e2881a22-9a86-4956-8abf-bfbaa4020b1c)

**Comment by Isakdl** [comment] 2024-01-18 10:42
Strange, even after adding `api` to the model, I cannot reproduce this issue. 

One note is that `api` has been deprecated in favor of the keyword `!persist`. And unless you have a table defined on the class it should not change anything on the generated code. The meaning here is that we do not want to store the field in the database.

**Comment by mike-novarca** [comment] 2024-01-18 10:43
persist requires a table definition. There is no table definition.

**Comment by Isakdl** [comment] 2024-01-18 10:45
@mike-novarca Indeed but `api` simply means that the value should not be stored in the database (hence the rename of the keyword).

**Comment by mike-novarca** [comment] 2024-01-18 10:46
Removing the factory constructor breaks the fromJson method

**Comment by mike-novarca** [comment] 2024-01-18 10:47
What generated code do you get?

**Comment by Isakdl** [comment] 2024-01-18 11:02
> Removing the factory constructor breaks the fromJson method

I meant only this part `Map<Object, Object> map,`

The full code would be:


```dart
factory FieldInputType({
    required _i2.InputValueType valueType,
    required String name,
    required String description,
    required String thumbnailUrl,
  }) = _FieldInputTypeImpl;
```

**Comment by mike-novarca** [comment] 2024-01-18 11:06
Deleting the generated file and regenerating now produces this :-

/* AUTOMATICALLY GENERATED CODE DO NOT MODIFY */
/*   To generate run: "serverpod generate"    */

// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: public_member_api_docs
// ignore_for_file: implementation_imports
// ignore_for_file: use_super_parameters
// ignore_for_file: type_literal_in_constant_pattern

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:serverpod_client/serverpod_client.dart' as _i1;
import 'protocol.dart' as _i2;

abstract class FieldInputType extends _i1.SerializableEntity {
  FieldInputType._({
    required this.valueType,
    required this.name,
    required this.description,
    required this.thumbnailUrl,
  });

  factory FieldInputType({
    required _i2.InputValueType valueType,
    required String name,
    required String description,
    required String thumbnailUrl,
  }) = _FieldInputTypeImpl;

  factory FieldInputType.fromJson(
    Map<String, dynamic> jsonSerialization,
    _i1.SerializationManager serializationManager,
  ) {
    return FieldInputType(
      valueType: serializationManager
          .deserialize<_i2.InputValueType>(jsonSerialization['valueType']),
      name: serializationManager.deserialize<String>(jsonSerialization['name']),
      description: serializationManager
          .deserialize<String>(jsonSerialization['description']),
      thumbnailUrl: serializationManager
          .deserialize<String>(jsonSerialization['thumbnailUrl']),
    );
  }

  _i2.InputValueType valueType;

  String name;

  String description;

  String thumbnailUrl;

  FieldInputType copyWith({
    _i2.InputValueType? valueType,
    String? name,
    String? description,
    String? thumbnailUrl,
  });
  @override
  Map<String, dynamic> toJson() {
    return {
      'valueType': valueType,
      'name': name,
      'description': description,
      'thumbnailUrl': thumbnailUrl,
    };
  }
}

class _FieldInputTypeImpl extends FieldInputType {
  _FieldInputTypeImpl({
    required _i2.InputValueType valueType,
    required String name,
    required String description,
    required String thumbnailUrl,
  }) : super._(
          valueType: valueType,
          name: name,
          description: description,
          thumbnailUrl: thumbnailUrl,
        );

  @override
  FieldInputType copyWith({
    _i2.InputValueType? valueType,
    String? name,
    String? description,
    String? thumbnailUrl,
  }) {
    return FieldInputType(
      valueType: valueType ?? this.valueType.copyWith(),
      name: name ?? this.name,
      description: description ?? this.description,
      thumbnailUrl: thumbnailUrl ?? this.thumbnailUrl,
    );
  }
}

**Comment by mike-novarca** [comment] 2024-01-18 11:06
The include is different

**Comment by mike-novarca** [comment] 2024-01-18 11:19
The error in the generated code has gone.

**Comment by Isakdl** [comment] 2024-01-18 11:52
Okay great 🚀! Closing this then!

**Closed by Isakdl** 2024-01-18 11:52 UTC
Labels: bug, need info
