### ISSUE TITLE
S3 upload fails with: "Connection reset by peer" on larger files

### ISSUE THREAD

**Issue by a1exhedb** [serverpod/serverpod#1610] opened 2023-11-28 02:43 UTC
I can upload files just fine below around 10mb to the AWS S3 bucket.
But when i try a larger file, not huge but around 15mb i get the error: Connection reset by peer

I did find it might be solved by adding: maxRequestSize: 52428800
to the development config file but maybe i'm missing something because that did not work for me.

Is there a file size upload limit imposed by Serverpod?

here uploadByteData fails, description type is set to multipart.
```
var uploadDescription = await client.service.cloudCreateUploadDescription(path);
if (uploadDescription == null) throw Exception('upload failed');
final uploader = FileUploader(uploadDescription);
final uploadResult = await uploader.uploadByteData(data);
final verifiedResult = await client.service.cloudVerifyUpload(path);
final publicUrl = await client.service.cloudPublicUrl(path);

if (!uploadResult || !verifiedResult || publicUrl == null) {
  throw Exception('upload failed');
}
return publicUrl;
```

**Comment by SandPod** [comment] 2024-12-18 21:44
Closing as duplicate of: https://github.com/serverpod/serverpod/issues/456

**Closed by SandPod** 2024-12-18 21:44 UTC
Labels: area: storage
