### ISSUE TITLE
serverpod  create second project :    psql: error:

### ISSUE THREAD

**Issue by woshids** [serverpod/serverpod#301] opened 2022-09-21 01:27 UTC
I used  serverpod  create second project :

Setting up Docker and default database tables in /home/nigel_macpro/WorkSpace/Dart/serverpod/mypod/mypod_server
If you run serverpod create for the first time, this can take a few minutes as Docker is downloading the images for Postgres. If you get stuck at this step, make sure that you have the latest version of Docker Desktop and that it is
currently running.

Starting docker
Creating mypod_server_postgres_1 ... done
Creating mypod_server_redis_1    ... done
Postgres is ready
psql: error: connection to server at "postgres" (172.19.0.3), port 5432 failed: FATAL:  password authentication failed for user "postgres"
Stopping docker
Stopping mypod_server_redis_1    ... done
Stopping mypod_server_postgres_1 ... done
Completed table setup exit code: 0
Cleaning up

SERVERPOD CREATED 🥳

All setup. You are ready to rock!

Start your Serverpod by running:

  $ cd mypod/mypod_server
  $ docker-compose up --build --detach
  $ dart bin/main.dart

**Comment by vlidholt** [comment] 2022-09-21 07:34
That is odd. Are you using the latest version of the serverpod command? (0.9.13 or later?). Do you have any other Docker containers running? What happens if you try to create a third project?

I've tested this extensively on my machine as I create projects all the time.

**Comment by woshids** [comment] 2022-09-22 00:36
I used the system is ubuntu20.04.When I used Ubuntu22.04 created first project same the situation (I think that problem is in the docker or docker-compose version ):
psql: error: connection to server at "postgres" (172.19.0.3), port 5432 failed: FATAL: password authentication failed for user

**Comment by vlidholt** [comment] 2022-09-22 06:39
This should be fixed in the latest version. If you do a `dart pub global activate serverpod_cli`, it will upgrade the tooling. Before this version, Serverpod didn't have proper support for Linux.

I'm closing this issue, please reopen if the problem is still there.

**Closed by vlidholt** 2022-09-22 06:39 UTC
Labels: need info
