### ISSUE TITLE
`Table.insert(session, row)` should update `row.id`

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#1224] opened 2023-07-30 03:53 UTC
**Is your feature request related to a problem? Please describe.**

When inserting a row into a table, currently there is no way to get the `id` of the newly-inserted row.

**Describe the solution you'd like**

It would be great if `insert` updated the `id` of the row.

Or, since having side effects on parameters is not pretty, maybe `insert` could return the `id` of the newly-inserted row. (Currently the return type is `Future<void>`, so this should be backwards-compatible.)

**Comment by Isakdl** [comment] 2023-07-31 08:13
Right now it does actually mutate the input variable and sets the `id`. But I agree not pretty and it would be better to return the value instead, I think I would prefer the entire object, but that can be debated.

**Comment by starklord** [comment] 2023-08-01 15:25
Hi, it would be great if the Insert method would return the new inserted object. By now many times i am doing this 3 steps:
1. insert the new object
2. find the new object, and the problem is that you cant find the new object by id so you have to find it making some tricks in the where clause and that should not be the way.
3. update the actual object to point the new object, and because the find method may return null you cant do this directly, you need to create a new object and then point to the actual object :S 
------------------------------------
So how should it be?, maybe:
Proposal A) myPerson = await Person.insert(session,myPerson);
Proposal B) myPerson.id = Person await Person.insert(session,myPerson);

**Comment by Isakdl** [comment] 2023-11-20 13:31
Fixed in the new api that now returns the entire inserted object (and does not mutate the old).

**Closed by Isakdl** 2023-11-20 13:31 UTC
