### ISSUE TITLE
Serverpod does not  support endpoint class  methoed return record type

### ISSUE THREAD

**Issue by 417052069** [serverpod/serverpod#2105] opened 2024-04-07 01:49 UTC
In my project  server endpoint class i build a method ,here is the code  in my accounting_endpoint.dart
  ```
Future<
      ({
        List<Accounting>? lists,
        double expense,
        double incoming,
      })> listDuration(Session session, DateTime start, DateTime end) async {
    final userId = await session.auth.authenticatedUserId;
    if (userId == null) {
      return (
        lists: null,
        expense: 0.0,
        incoming: 0.0,
      );
    }

    final res = await Accounting.db.find(session,
        where: (item) => item.userId.equals(userId) & item.date.between(start, end),
        orderBy: (item) => item.date);

    if (res.isNotEmpty) {
      double expenseAmount = 0;
      double incomingAmount = 0;
      for (var accounting in res) {
        if (accounting.type == AccountingInOrOutType.incoming) {
          expenseAmount += accounting.amount;
        } else {
          incomingAmount += accounting.amount;
        }
      }

      return (
        lists: res,
        expense: expenseAmount,
        incoming: incomingAmount,
      );
      // return;
    }
    return (
      lists: null,
      expense: 0.0,
      incoming: 0.0,
    );
  }
```

when  i run serverpod generate ,it show error below:

Found 1 issue.
**_Error on line 138, column 11 of package:chat_app_server/src/endpoints/accounting_endpoint.dart: The type "({double expense, double incoming, List<Accounting>? lists})" is not a supported endpoint return type.
    ╷
138 │       })> listDuration(Session session, DateTime start, DateTime end) async {
    │           ^^^^^^^^^^^^
    ╵
✗ Generating code (0.4s)
Incremental code generation complete._**
![issue](https://github.com/serverpod/serverpod/assets/96505384/34e50098-795a-436f-81e8-ba2cbca98b89)

**Serverpod versions**
Serverpod version: 1.2.6
Flutter 3.19.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 68bfaea224 (2 weeks ago) • 2024-03-20 15:36:31 -0700
Engine • revision a5c24f538d
Tools • Dart 3.3.2 • DevTools 2.31.1

i'm on ubuntu 22.04

**Comment by SandPod** [comment] 2024-04-09 15:35
Hey @417052069 👋 

Thanks for the report.

This is already reported so I will close this as a duplicate of https://github.com/serverpod/serverpod/issues/588

**Closed by SandPod** 2024-04-09 15:35 UTC

**Comment by 417052069** [comment] 2024-04-10 06:39
ok,thank you.
