### ISSUE TITLE
Support `Set` type in model yaml

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#1915] opened 2024-02-14 02:04 UTC
**Is your feature request related to a problem? Please describe.**

This works in a `.spy.yaml` (where `FileType` is a Serverpod enum):

```yaml
  urls: Map<FileType, String>?
```

However, this does not work:

```yaml
  uploadedTypes: Set<FileType>?
```

This gives the error `The type "Set" cannot have generic types defined.`

Probably `Set<K>` should be serialized to JSON as `Map<K, bool>`. I believe support was added to Serverpod recently to handle map keys of types other than String and int, so maybe this is supportable in a generic way now.

Or the set values could be stored as a JSON array, and added back to a `Set` on deserialization.

**Comment by Isakdl** [comment] 2024-02-20 11:42
Related issue: https://github.com/serverpod/serverpod/issues/1784

**Comment by lukehutch** [comment] 2024-07-14 01:13
Also, trying to call an endpoint with a `Set`-typed parameter gives the following failure (which is worse, because it is a runtime failure, it is not detected during `serverpod generate`):

```
Converting object to an encodable object failed: _Set len:1
```

**Comment by SandPod** [comment] 2024-12-19 16:09
Closing as duplicate of: https://github.com/serverpod/serverpod/issues/1784

**Closed by SandPod** 2024-12-19 16:09 UTC
