### ISSUE TITLE
Adding "defaultValue" keyword in the protocal folder files.

### ISSUE THREAD

**Issue by ibrahimdevoloper** [serverpod/serverpod#676] opened 2023-02-18 19:10 UTC
Hi, 
My name is Ibrahim.

I am considering using Serverpod for future projects, and I have suggestion about a feature.

### Can you add "defaultValue" keyword?
A "defaultValue" keyword would be useful for setting a default value for a field.

### The usage
The use of such keyword should be similar to 
`postId: int, parent=posts`
in the corresponded file.
for example:
`commentCount: int, defaultValue=0`

Thanks for such great project

**Comment by vlidholt** [comment] 2023-02-18 21:36
Thank you for the suggestion! I'm going to close this issue as it is a duplicate of #236 and there is a bit more discussion there. :)

**Closed by vlidholt** 2023-02-18 21:36 UTC
Labels: duplicate
