### ISSUE TITLE
Add method on Users class to delete a user.

### ISSUE THREAD

**Issue by vlidholt** [serverpod/serverpod#1119] opened 2023-07-11 13:06 UTC
There should be a method for permanently deleting users on the `Users` class in the auth module. See discussion:

### Discussed in https://github.com/serverpod/serverpod/discussions/1096

<div type='discussions-op-text'>

<sup>Originally posted by **Frank1016** July  7, 2023</sup>
Hi, because I don't have any clue on how to delete account through EmailAuthController API calls, I tried to delete an account line directly in the database table "serverpod_user_info". However, after doing so, I cannot create another account using the same email address, and the error is about some duplicated ID. Could anyone tell me how to completely delete a registered account through EmailAuthController()?</div>

**Comment by lukehutch** [comment] 2023-07-11 19:52
This method should also delete the user's profile image, and (probably also) any files uploaded by the user. However, first the userId that uploaded a given file needs to be tracked: See #922.

**Comment by dkbast** [comment] 2024-04-10 19:37
I think there should also be the following functionality:

1)  a "soft-delete" which only disables the user account 
2) a "anonymise-instead-of-delete" (Sometimes we want to (and are allowed to) keep the users data but need to make sure that there is no personal information left - in these cases overwriting the user info but keeping the "row in the database" can be utilised.
3) a "onDeleteUser" callback where we can register some logic which is triggered by this method. This makes it easier to clean up the database etc.

**Comment by SandPod** [comment] 2024-12-18 20:54
Closing as duplicate of: https://github.com/serverpod/serverpod/issues/791

**Closed by SandPod** 2024-12-18 20:54 UTC
Labels: enhancement
