### ISSUE TITLE
Add support for immutable models

### ISSUE THREAD

**Issue by vlidholt** [serverpod/serverpod#1864] opened 2024-02-05 20:23 UTC
There should be a way to declare models to be immutable. Perhaps by adding a keyword to the model files:

```yaml
class: MyModel
immutable: true
fields:
  myField:int
```

Then we can also support equality and hash.

**Comment by Isakdl** [comment] 2024-02-07 08:15
Other existing issue: https://github.com/serverpod/serverpod/issues/1359

**Comment by dHanel** [comment] 2024-10-22 17:09
implementing a copyWith and (de)serialization would be good aswell

**Comment by Isakdl** [comment] 2024-10-23 12:08
@dHanel That is already supported https://docs.serverpod.dev/concepts/models#copywith, serialization is also a core feature in Serverpod and has full support.

**Comment by SandPod** [comment] 2024-12-19 16:02
Closing as duplicate of: https://github.com/serverpod/serverpod/issues/1359

**Closed by SandPod** 2024-12-19 16:02 UTC
Labels: enhancement
