### ISSUE TITLE
Serverpod Generate

### ISSUE THREAD

**Issue by lastmeta** [serverpod/serverpod#502] opened 2022-12-19 20:04 UTC
```
PS C:\moontree\server2\serverv2_server> serverpod generate
WARNING! Windows is not officially supported yet. Things may or may not work as expected.

Running serverpod generate.
Failed to generate lib\src\generated\asset_class.dart
Yikes! It is possible that this error is caused by an internal issue with the
Serverpod tooling. We would appreciate if you filed an issue over at Github. Please   
include the stack trace below and describe any steps you did to trigger the error.    
https://github.com/serverpod/serverpod/issues
FileSystemException: Cannot create file, path = 'lib\src\generated\asset_class.dart' (OS Error: The system cannot find the path specified.
, errno = 3)
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.createSync (dart:io/file_impl.dart:273:5)
#2      ClassGenerator.generate (file:///C:/Users/jorda/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/serverpod_cli-0.9.20/bin/generator/class_generator.dart:72:20)      
#3      performGenerateClasses (file:///C:/Users/jorda/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/serverpod_cli-0.9.20/bin/generator/class_generator.dart:28:19)       
#4      performGenerate (file:///C:/Users/jorda/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/serverpod_cli-0.9.20/bin/generator/generator.dart:56:3)
<asynchronous suspension>
#5      _main (file:///C:/Users/jorda/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/serverpod_cli-0.9.20/bin/serverpod_cli.dart:201:7)
<asynchronous suspension>
#6      main.<anonymous closure> (file:///C:/Users/jorda/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/serverpod_cli-0.9.20/bin/serverpod_cli.dart:33:9)
<asynchronous suspension>
#7      main (file:///C:/Users/jorda/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/serverpod_cli-0.9.20/bin/serverpod_cli.dart:30:3)
<asynchronous suspension>


Failed to generate lib\src\generated\asset_metadata_class.dart
Yikes! It is possible that this error is caused by an internal issue with the
Serverpod tooling. We would appreciate if you filed an issue over at Github. Please   
include the stack trace below and describe any steps you did to trigger the error.    
https://github.com/serverpod/serverpod/issues
FileSystemException: Cannot create file, path = 'lib\src\generated\asset_metadata_class.dart' (OS Error: The system cannot find the path specified.
, errno = 3)
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.createSync (dart:io/file_impl.dart:273:5)
#2      ClassGenerator.generate (file:///C:/Users/jorda/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/serverpod_cli-0.9.20/bin/generator/class_generator.dart:72:20)      
#3      performGenerateClasses (file:///C:/Users/jorda/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/serverpod_cli-0.9.20/bin/generator/class_generator.dart:28:19)       
#4      performGenerate (file:///C:/Users/jorda/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/serverpod_cli-0.9.20/bin/generator/generator.dart:56:3)
<asynchronous suspension>
#5      _main (file:///C:/Users/jorda/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/serverpod_cli-0.9.20/bin/serverpod_cli.dart:201:7)
<asynchronous suspension>
#6      main.<anonymous closure> (file:///C:/Users/jorda/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/serverpod_cli-0.9.20/bin/serverpod_cli.dart:33:9)
<asynchronous suspension>
#7      main (file:///C:/Users/jorda/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/serverpod_cli-0.9.20/bin/serverpod_cli.dart:30:3)
<asynchronous suspension>
...
```
seemed to work fine after I manually made the `generated` folder (which wasn't present because it is .gitignored).

might just want to create this folder at the beginning of the process if it isn't there.

**Comment by AndryHTC** [comment] 2022-12-19 20:58
@lastmeta it may be a duplicate of https://github.com/serverpod/serverpod/issues/336?

**Comment by AndryHTC** [comment] 2022-12-19 20:59
@lastmeta may it be a duplicate of https://github.com/serverpod/serverpod/issues/336?

**Comment by lastmeta** [comment] 2022-12-19 22:51
> @lastmeta may it be a duplicate of #336?

looks like it

**Comment by yahu1031** [comment] 2022-12-20 08:06
@lastmeta Ideally they must create if they don't exist. Can you able to recreate this with the latest version?

**Comment by vlidholt** [comment] 2022-12-20 14:36
Closing this as it is a duplicate.

**Closed by vlidholt** 2022-12-20 14:36 UTC

**Comment by lastmeta** [comment] 2022-12-20 14:48
> @lastmeta Ideally they must create if they don't exist. Can you able to recreate this with the latest version?

Who is they? The user? I think got ignoring generated files is quite common so ideally the code should handle this case.

**Comment by yahu1031** [comment] 2022-12-20 15:20
@lastmeta Nope, gitignore wasn't configured that way. They - generated folder & files. But anyhow, can you try this with serverpod - `0.9.21`.

**Comment by lastmeta** [comment] 2022-12-20 15:28
> @lastmeta Nope, gitignore wasn't configured that way. They - generated folder & files. But anyhow, can you try this with serverpod - `0.9.21`.

I've already solved the issue manually, why don't you recreate it and try it on the latest version?

**Comment by yahu1031** [comment] 2022-12-20 16:56
> why don't you recreate it and try it on the latest version?

Sorry, buddy. I currently don't have windows machine.

**Comment by yahu1031** [comment] 2022-12-20 16:58
@vlidholt I think this can be opened back cause the parent ticket was closed. And may be you can let it stay closed cause the issue wasn't able to reproduced.

**Comment by lastmeta** [comment] 2022-12-21 17:14
> > why don't you recreate it and try it on the latest version?
> 
> Sorry, buddy. I currently don't have windows machine.

I just noticed I've been on version 0.9.21 this whole time.

**Comment by yahu1031** [comment] 2022-12-21 18:40
perfect will cross-check this. Gimme a while. @lastmeta

**Comment by yahu1031** [comment] 2022-12-21 19:18
Hey @lastmeta, Looks like things are working perfectly fine.

```cmd
C:\Users\WDAGUtilityAccount\Desktop\heypod>serverpod version
WARNING! Windows is not officially supported yet. Things may or may not work as expected.

Serverpod version: 0.9.21

C:\Users\WDAGUtilityAccount\Desktop\heypod>cd heypod_server
C:\Users\WDAGUtilityAccount\Desktop\heypod\heypod_server>cd lib/src

C:\Users\WDAGUtilityAccount\Desktop\heypod\heypod_server\lib\src>dir                                                     
  Volume in drive C has no label.                                                                                         
  Volume Serial Number is 8496-FCB6                                                                          


Directory of C:\Users\WDAGUtilityAccount\Desktop\heypod\heypod_server\lib\src      
12/22/2022  12:32 AM    <DIR>          .                                  
12/22/2022  12:32 AM    <DIR>          ..                                 
12/22/2022  12:29 AM    <DIR>          endpoints                            
12/22/2022  12:29 AM    <DIR>          future_calls                                                 
12/22/2022  12:29 AM    <DIR>          protocol                                                 
12/22/2022  12:29 AM    <DIR>          web                                               
               0 File(s)              0 bytes                                                         
               6 Dir(s)  38,525,435,904 bytes free                                                   

👆🏻👆🏻👆🏻👆🏻👆🏻👆🏻 Notice that I deleted generated folder from lib/src 👆🏻👆🏻👆🏻👆🏻👆🏻👆🏻

C:\Users\WDAGUtilityAccount\Desktop\heypod\heypod_server\lib\src>cd ../..         

C:\Users\WDAGUtilityAccount\Desktop\heypod\heypod_server>serverpod generate       
WARNING! Windows is not officially supported yet. Things may or may not work as expected.     

Running serverpod generate.                                                                 
Done.                                                                                     

C:\Users\WDAGUtilityAccount\Desktop\heypod\heypod_server> 
```

### System Info
**Edition**: `Windows 10 Enterprise`
**Version**: `2004`
**Installed on**: `12/2/2022`
**OS Build**: `19041.2346`
**Experience**: `Windows Feature Experience Pack 120.2212.4190.0`

PS: I'm soo worried cause I wrote the fix for it.
