### ISSUE TITLE
add the "in"  expression

### ISSUE THREAD

**Issue by starklord** [serverpod/serverpod#1045] opened 2023-06-26 16:25 UTC
Hi, it would be great if you add the IN expression inside the where clause,
example: 
where: (employee)=>employee.id.in(allowedIds)

**Comment by Kstev239** [comment] 2023-06-29 10:48
Probably duplicate of #238

**Comment by SandPod** [comment] 2023-08-25 07:43
Closed as duplicate of: https://github.com/serverpod/serverpod/issues/238

**Closed by SandPod** 2023-08-25 07:43 UTC
Labels: enhancement
