### ISSUE TITLE
Geospatial Queries like the ones in MongoDB

### ISSUE THREAD

**Issue by Shiba-Kar** [serverpod/serverpod#2946] opened 2024-11-08 13:29 UTC
https://www.mongodb.com/docs/manual/geospatial-queries/#geospatial-queries

**Comment by binemmanuel** [comment] 2024-11-09 08:03
I used Firebase for this one my app, if only Serverpod had support for it

**Comment by SandPod** [comment] 2024-11-11 15:48
This is a duplicate of the issue tracked here, closing as duplicate: https://github.com/serverpod/serverpod/issues/2439

This is something we will add support for in the future.

**Closed by SandPod** 2024-11-11 15:48 UTC
