### ISSUE TITLE
make the 'id' field the equality factor

### ISSUE THREAD

**Issue by starklord** [serverpod/serverpod#1071] opened 2023-07-05 02:14 UTC
Hi, it would be very helpful if the database objects could use the equatable package or some equivalent to make the 'id' field as the key value for == operator.
by now serverpod uses id as primary key, so this could be used as the hashcode equality implementation by default or maybe in the entity.yaml file this could be selected or not by the developer.

**Comment by lukehutch** [comment] 2023-07-05 06:12
This would only make sense if database-sourced objects were immutable (which they are not...)

**Comment by starklord** [comment] 2023-07-05 15:27
The problem is just comparing objects, thats all, there are scenarios when you want A == B return true if A.id == B.id
by now in serverpod you can't touch the shared object, thats why it should be helpful if in the entity.yaml file you would be able to do that.

**Comment by lukehutch** [comment] 2023-07-05 20:59
In general `A == B` is not true just because `A.id == B.id`.

The only way an `==` method should compare only `id` would be if there was no public constructor for these protocol objects, and if they can only be obtained directly from a database query. But even then, if you run the same database query twice, fields other than `id` could easily change between the two queries. Therefore, for value equality, for all fields should be compared, not just `id`.

I checked and the default generated protocol classes do not implement `hashCode` or `==`. That means that the default of reference equality applies.

Maybe there should be a flag that should be added to protocol yaml files that causes these two methods to be defined, to give value equality semantics. Or maybe that should even be the default.

However `hashCode` and `==` would need to compare all fields, not just `id`.

**Comment by starklord** [comment] 2023-07-06 01:11
Just to clarify your question about the same query twice because i think that explains the point better:
for example the first query returns A{id = 10, A.name = 'evan'}

**Comment by SandPod** [comment] 2024-12-18 15:42
@starklord Thank you for the suggested feature!

However, this is not a direction we are expected to take. I believe only comparing the `id` field of a model would result in unexpected behavior for most cases, even if the models were immutable.

I think the solution that @lukehutch suggests should be sufficient, `object1.id == object2.id`, if this is the desired behavior. We will close this issue as a `won't fix` to make our intention clear.

**Closed by SandPod** 2024-12-18 15:42 UTC
Labels: area: models
