### ISSUE TITLE
Repair migrations are impossible to create

### ISSUE THREAD

**Issue by mike-novarca** [serverpod/serverpod#1814] opened 2024-01-24 14:27 UTC
**Describe the bug**
When trying to create a repair migration it just gives error of not being able to connect to the server even though the server is running

**To Reproduce**
1. try to create a repair migration. error occurs, 

**Expected behavior**
repair created

**Screenshots**
If applicable, add screenshots to help e
![Screenshot 2024-01-24 at 14 25 50](https://github.com/serverpod/serverpod/assets/120393194/8a09d2b6-5583-42b2-8055-e28676f8bc1b)
xplain your problem.

**Serverpod versions**
 -  _CLI Version:_ Run `serverpod version` to determine the version of installed tooling.
 - _Library version:_ Check the pubspec.yaml file for the version of Serverpod you are using.

**Platform information**
On which platforms do you experience the issue. Please provide as much information here as you can. Where are you running the server, which front end device are you using?

**Additional context**

**Comment by Isakdl** [comment] 2024-01-25 09:16
What version are you on? We had a small bug that we fixed in 1.2.1 see issue: https://github.com/serverpod/serverpod/discussions/1765

Was resolved in this PR: https://github.com/serverpod/serverpod/issues/1773#issuecomment-1895633427

If you are on 1.2.1 could you please explain the sequence of steps you took to get this error.

**Comment by mike-novarca** [comment] 2024-01-25 10:15
I'm on 1.2.1. I launched the server then in a separate terminal in the same directory I ran the repair migration and got the error.

**Comment by Isakdl** [comment] 2024-06-25 09:19
Closing because of no reproducibility, reopen if you encounter this again.

**Closed by Isakdl** 2024-06-25 09:19 UTC
Labels: need info
