### ISSUE TITLE
Need to join automatically

### ISSUE THREAD

**Issue by jijkbird** [serverpod/serverpod#697] opened 2023-02-28 08:27 UTC
I need to query the automatic join function. For example, a list contains multiple object data. If the automatic join is not available, the client can only request the included data multiple times. This request volume will be very large, causing serious performance problems to the backend.

**Comment by vlidholt** [comment] 2023-03-03 21:38
For most use cases, this approach combined with caching will be sufficient. If you need to do proper joins, you can always use custom sql queries.

A step closer to this will be added support for views.

**Comment by pro100andrey** [comment] 2023-05-20 19:18
Hello everyone, someone might find it useful to have an extension that provides a simple way to join 2 tables with logging capabilities and returning typed data.

Example how to use:

``` dart
    final databaseConnection = await session.db.databaseConnection;

    final items = await databaseConnection.join(
      session: session,
      orderDescending: true,
      orderBy: Post.t.created,
      limit: page.limit,
      offset: page.offset,
      where: (t) => t.userId.equals(userId),
      t1: Post.t,
      t2: UserInfo.t,
      relation: (t1, t2) => (t1.userId, t2.id),
      fromJson: () => (Post.fromJson, UserInfo.fromJson),
    );
```

Extension (dart 3):

``` dart

extension DatabaseJoin on DatabaseConnection {
  // ignore: long-parameter-list
  Future<(List<TR1>, List<TR2>)> join<T1 extends Table, T2 extends Table,
      TR1 extends TableRow, TR2 extends TableRow>({
    required Session session,
    required T1 t1,
    required T2 t2,
    required (Column, Column) Function(T1 t1, T2 t2) relation,
    required (FromJson<TR1>, FromJson<TR2>) Function() fromJson,
    Function(T1)? where,
    int? limit,
    int? offset,
    Column? orderBy,
    List<Order>? orderByList,
    bool orderDescending = false,
    Transaction? transaction,
  }) async {
    assert(
      orderByList == null || orderBy == null,
      'orderByList or orderBy should be null',
    );

    final startTime = DateTime.now();

    final rel = relation(t1, t2);
    final relStr = 't1.${rel.$1.expression} = t2.${rel.$2.expression}';

    final order = orderBy != null
        ? "ORDER BY t1.$orderBy ${orderDescending ? 'DESC ' : ''}"
        : '';

    final query = 'SELECT t1.*, t2.* '
        'FROM ${t1.tableName} t1 '
        'JOIN ${t2.tableName} t2 ON $relStr '
        '${where != null ? "WHERE t1.${where(t1)} " : ''}'
        '$order'
        '${limit != null ? "LIMIT $limit " : ''}'
        '${offset != null ? "OFFSET $offset " : ''}';

    final context =
        transaction != null ? transaction.postgresContext : postgresConnection;

    try {
      final result = await context.mappedResultsQuery(
        query,
        allowReuse: false,
        timeoutInSeconds: 60,
      );

      final t1Result = <TR1>[];
      final t2Result = <int, TR2>{};

      final serializationManager = poolManager.serializationManager;

      final parser = fromJson();
      for (final r in result) {
        final tr1 = parser.$1(r[t1.tableName]!.parse(), serializationManager);
        final tr2 = parser.$2(r[t2.tableName]!.parse(), serializationManager);

        t1Result.add(tr1);
        t2Result[tr2.id!] = tr2;
      }

      await _logQuery(
        session,
        query,
        startTime,
        numRowsAffected: t1Result.length + t2Result.length,
      );

      return (t1Result, t2Result.values.toList(growable: false));
    } on Exception catch (e, trace) {
      await _logQuery(session, query, startTime, exception: e, trace: trace);

      rethrow;
    }
  }

// ignore: long-parameter-list
  Future<void> _logQuery(
    Session session,
    String query,
    DateTime startTime, {
    int? numRowsAffected,
    Object? exception,
    StackTrace? trace,
  }) async {
    // Check if this query should be logged.
    final logSettings = session.serverpod.logManager.getLogSettingsForSession(
      session,
    );

    final duration =
        DateTime.now().difference(startTime).inMicroseconds / 1000000.0;
    final slow = duration >= logSettings.slowQueryDuration;
    // ignore: invalid_use_of_internal_member
    final shouldLog = session.serverpod.logManager.shouldLogQuery(
      session: session,
      slow: slow,
      failed: exception != null,
    );

    if (!shouldLog) {
      return;
    }

    // Use the current stack trace if there is no exception.
    trace ??= StackTrace.current;

    // Log the query.
    final entry = QueryLogEntry(
      // ignore: invalid_use_of_internal_member
      sessionLogId: session.sessionLogs.temporarySessionId,
      serverId: session.server.serverId,
      query: query,
      duration: duration,
      numRows: numRowsAffected,
      error: exception?.toString(),
      stackTrace: trace.toString(),
      slow: slow,
      // ignore: invalid_use_of_internal_member
      order: session.sessionLogs.currentLogOrderId,
    );
    // ignore: invalid_use_of_internal_member
    await session.serverpod.logManager.logQuery(session, entry);
    // ignore: invalid_use_of_internal_member
    session.sessionLogs.currentLogOrderId += 1;
    // ignore: invalid_use_of_internal_member
    session.sessionLogs.numQueries += 1;
  }
}

extension _MapFormat on Map<String, dynamic> {
  Map<String, dynamic> parse() {
    final data = <String, dynamic>{};

    for (final columnName in keys) {
      final value = this[columnName] as Object?;

      if (value is DateTime) {
        data[columnName] = value.toIso8601String();
      } else if (value is Uint8List) {
        final byteData = ByteData.view(
          value.buffer,
          value.offsetInBytes,
          value.length,
        );
        data[columnName] = byteData.base64encodedString();
      } else {
        data[columnName] = value;
      }
    }

    return data;
  }
}

```

**Comment by SandPod** [comment] 2023-08-25 07:34
I think this is a duplicate of: https://github.com/serverpod/serverpod/issues/1151

**Closed by SandPod** 2023-08-25 07:34 UTC
Labels: enhancement
