### ISSUE TITLE
serverpod generate doesn't working after I deleted another yaml code and created new one

### ISSUE THREAD

**Issue by Erekushin** [serverpod/serverpod#1668] opened 2023-12-14 03:56 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Serverpod versions**
 -  _CLI Version:_ Run `serverpod version` to determine the version of installed tooling.
 - _Library version:_ Check the pubspec.yaml file for the version of Serverpod you are using.

**Platform information**
On which platforms do you experience the issue. Please provide as much information here as you can. Where are you running the server, which front end device are you using?

**Additional context**

**Comment by SandPod** [comment] 2023-12-14 07:28
Hey @Erekushin!
Thanks for filing this bug.

My hunch tells me that this is a dupe of https://github.com/serverpod/serverpod/issues/1169, would you agree?
It not, could you provide some more information what differentiates it?

**Comment by SandPod** [comment] 2024-01-12 15:41
Closing since #1169 is already resolved.

**Closed by SandPod** 2024-01-12 15:41 UTC
Labels: question
